name: annotated-butd
channels:
  - pytorch
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - icu=58.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2019.4
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytorch=1.5.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=47.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.3
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - torchvision=0.6.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - future==0.18.2
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.30.0
    - h5py==2.10.0
    - idna==2.10
    - markdown==3.2.2
    - mypy-extensions==0.4.3
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==0.8.3
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tqdm==4.47.0
    - typed-argument-parser==1.5.0
    - typing-extensions==3.7.4.2
    - typing-inspect==0.6.0
    - urllib3==1.25.9
    - werkzeug==1.0.1

